"""Point-in-time research transforms with explicit temporal policy."""

from persistra.research.evaluation import (
    adjust_pvalues,
    compare_benchmark,
    information_coefficients,
    quantile_portfolios,
    summarize_groups,
)
from persistra.research.factor_models import (
    build_factor_risk_model,
    estimate_cross_sectional_factor_returns,
    fama_macbeth_regression,
    fit_time_series_factor_model,
    rolling_time_series_factor_model,
    summarize_factor_premia,
)
from persistra.research.factor_portfolio import (
    attribute_factor_portfolio,
    build_factor_portfolio_forecast,
)
from persistra.research.features import (
    build_feature_panel,
    project_vintage_history,
    select_vintage,
)
from persistra.research.labels import forward_returns
from persistra.research.manifest import (
    create_research_manifest,
    environment_distributions,
    environment_versions,
    identify_artifact,
    manifest_from_json,
    manifest_to_json,
    read_research_manifest,
    write_research_manifest,
)
from persistra.research.model import (
    ArtifactIdentity,
    BenchmarkComparison,
    CrossSectionalFactorModelResult,
    DatasetScope,
    FactorPortfolioAttribution,
    FactorPortfolioForecast,
    FactorPremiaResult,
    FactorRegressionResult,
    FactorRiskModel,
    FamaMacBethResult,
    FeaturePanel,
    FeaturePolicy,
    FeatureSpec,
    ForwardReturnLabels,
    GroupSignalResult,
    InformationCoefficientResult,
    MultipleTestingResult,
    QuantilePortfolioResult,
    RegressionCovariance,
    ResearchManifest,
    ResearchSummary,
    RollingFactorRegressionResult,
    TemporalSplit,
    VintagePolicy,
    VintageSelection,
)
from persistra.research.splits import (
    expanding_window_splits,
    rolling_window_splits,
    validate_temporal_split,
)
from persistra.research.summary import summarize_regimes
from persistra.research.transforms import (
    clip_cross_section,
    neutralize_cross_section,
    rank_cross_section,
    standardize_cross_section,
)

__all__ = [
    "ArtifactIdentity",
    "BenchmarkComparison",
    "CrossSectionalFactorModelResult",
    "DatasetScope",
    "FactorPortfolioAttribution",
    "FactorPortfolioForecast",
    "FactorPremiaResult",
    "FactorRegressionResult",
    "FactorRiskModel",
    "FamaMacBethResult",
    "FeaturePanel",
    "FeaturePolicy",
    "FeatureSpec",
    "ForwardReturnLabels",
    "GroupSignalResult",
    "InformationCoefficientResult",
    "MultipleTestingResult",
    "QuantilePortfolioResult",
    "RegressionCovariance",
    "ResearchManifest",
    "ResearchSummary",
    "RollingFactorRegressionResult",
    "TemporalSplit",
    "VintagePolicy",
    "VintageSelection",
    "adjust_pvalues",
    "attribute_factor_portfolio",
    "build_factor_portfolio_forecast",
    "build_factor_risk_model",
    "build_feature_panel",
    "clip_cross_section",
    "compare_benchmark",
    "create_research_manifest",
    "environment_distributions",
    "environment_versions",
    "estimate_cross_sectional_factor_returns",
    "expanding_window_splits",
    "fama_macbeth_regression",
    "fit_time_series_factor_model",
    "forward_returns",
    "identify_artifact",
    "information_coefficients",
    "manifest_from_json",
    "manifest_to_json",
    "neutralize_cross_section",
    "project_vintage_history",
    "quantile_portfolios",
    "rank_cross_section",
    "read_research_manifest",
    "rolling_time_series_factor_model",
    "rolling_window_splits",
    "select_vintage",
    "standardize_cross_section",
    "summarize_factor_premia",
    "summarize_groups",
    "summarize_regimes",
    "validate_temporal_split",
    "write_research_manifest",
]
