"""Public typed exception namespace."""

from persistra._errors import PersistraError
from persistra.domain.errors import (
    CurrencyMismatchError,
    DecimalOverflowError,
    DomainValidationError,
    DuplicateEventError,
    DurationOverflowError,
    InvalidContentIdError,
    InvalidCurrencyError,
    InvalidDecimalError,
    InvalidDurationError,
    InvalidEntityIdError,
    InvalidEventError,
    InvalidInstantError,
    InvalidIntervalError,
    InvalidPriceError,
    InvalidQualifiedNameError,
    InvalidQuantityError,
    NaiveDatetimeError,
    PrecisionLossError,
    UnitMismatchError,
    UnknownEventTypeError,
    UnsupportedSchemaVersionError,
)

__all__ = [
    "CurrencyMismatchError",
    "DecimalOverflowError",
    "DomainValidationError",
    "DuplicateEventError",
    "DurationOverflowError",
    "InvalidContentIdError",
    "InvalidCurrencyError",
    "InvalidDecimalError",
    "InvalidDurationError",
    "InvalidEntityIdError",
    "InvalidEventError",
    "InvalidInstantError",
    "InvalidIntervalError",
    "InvalidPriceError",
    "InvalidQualifiedNameError",
    "InvalidQuantityError",
    "NaiveDatetimeError",
    "PersistraError",
    "PrecisionLossError",
    "UnitMismatchError",
    "UnknownEventTypeError",
    "UnsupportedSchemaVersionError",
]
