"""Versioned dataframe contracts for canonical economic-data families."""

from __future__ import annotations

from persistra.domain import QualifiedName, SchemaVersion
from persistra.domain.frames import (
    FRAME_REGISTRY,
    ColumnDtype,
    ColumnSpec,
    FrameContract,
)


def _frame(
    name: str,
    columns: tuple[tuple[str, ColumnDtype], ...],
    ordering: tuple[str, ...],
) -> FrameContract:
    return FRAME_REGISTRY.register(
        FrameContract(
            QualifiedName(name),
            SchemaVersion(1),
            tuple(ColumnSpec(column, dtype) for column, dtype in columns),
            ordering,
        )
    )


FILINGS_FRAME = _frame(
    "persistra.dataframe.filings",
    (
        ("canonical_revision_id", ColumnDtype.STRING),
        ("filing_id", ColumnDtype.STRING),
        ("report_id", ColumnDtype.STRING),
        ("issuer_id", ColumnDtype.STRING),
        ("source_id", ColumnDtype.STRING),
        ("accession_namespace", ColumnDtype.STRING),
        ("normalized_accession", ColumnDtype.STRING),
        ("form_type", ColumnDtype.STRING),
        ("filing_status", ColumnDtype.STRING),
        ("filing_date", ColumnDtype.DATE),
        ("accepted_at", ColumnDtype.INSTANT),
        ("report_period_start", ColumnDtype.DATE),
        ("report_period_end", ColumnDtype.DATE),
        ("fiscal_year", ColumnDtype.INT),
        ("fiscal_period_kind", ColumnDtype.STRING),
        ("is_amendment", ColumnDtype.BOOL),
        ("amends_filing_id", ColumnDtype.STRING),
        ("taxonomy_namespace", ColumnDtype.STRING),
        ("taxonomy_version", ColumnDtype.STRING),
        ("document_content_id", ColumnDtype.STRING),
        ("document_redistributable", ColumnDtype.BOOL),
        ("available_at", ColumnDtype.INSTANT),
        ("availability_quality", ColumnDtype.STRING),
        ("safety_status", ColumnDtype.STRING),
    ),
    ("issuer_id", "report_period_end", "accepted_at", "canonical_revision_id"),
)

RAW_FACTS_FRAME = _frame(
    "persistra.dataframe.fundamental_raw",
    (
        ("canonical_revision_id", ColumnDtype.STRING),
        ("filing_id", ColumnDtype.STRING),
        ("report_id", ColumnDtype.STRING),
        ("issuer_id", ColumnDtype.STRING),
        ("source_id", ColumnDtype.STRING),
        ("taxonomy_namespace", ColumnDtype.STRING),
        ("taxonomy_version", ColumnDtype.STRING),
        ("source_concept_name", ColumnDtype.STRING),
        ("period_kind", ColumnDtype.STRING),
        ("period_start", ColumnDtype.DATE),
        ("period_end", ColumnDtype.DATE),
        ("period_policy_content_id", ColumnDtype.STRING),
        ("fiscal_year", ColumnDtype.INT),
        ("fiscal_period_kind", ColumnDtype.STRING),
        ("numeric_kind", ColumnDtype.STRING),
        ("value", ColumnDtype.FLOAT),
        ("is_nil", ColumnDtype.BOOL),
        ("nil_reason_code", ColumnDtype.STRING),
        ("unit_name", ColumnDtype.STRING),
        ("currency", ColumnDtype.STRING),
        ("source_decimals", ColumnDtype.INT),
        ("source_precision", ColumnDtype.INT),
        ("dimensions", ColumnDtype.JSON),
        ("accepted_at", ColumnDtype.INSTANT),
        ("available_at", ColumnDtype.INSTANT),
        ("availability_quality", ColumnDtype.STRING),
        ("safety_status", ColumnDtype.STRING),
    ),
    (
        "issuer_id",
        "period_end",
        "period_start",
        "taxonomy_namespace",
        "taxonomy_version",
        "source_concept_name",
        "canonical_revision_id",
    ),
)

ESTIMATES_FRAME = _frame(
    "persistra.dataframe.estimates_individual",
    (
        ("canonical_revision_id", ColumnDtype.STRING),
        ("estimate_measure_id", ColumnDtype.STRING),
        ("measure_version", ColumnDtype.INT),
        ("measure_name", ColumnDtype.STRING),
        ("subject_entity_kind", ColumnDtype.STRING),
        ("subject_entity_id", ColumnDtype.STRING),
        ("estimate_contributor_id", ColumnDtype.STRING),
        ("source_id", ColumnDtype.STRING),
        ("numeric_kind", ColumnDtype.STRING),
        ("target_kind", ColumnDtype.STRING),
        ("target_fiscal_year", ColumnDtype.INT),
        ("target_fiscal_period_kind", ColumnDtype.STRING),
        ("target_period_end", ColumnDtype.DATE),
        ("horizon_days", ColumnDtype.INT),
        ("target_at", ColumnDtype.INSTANT),
        ("value", ColumnDtype.FLOAT),
        ("unit_name", ColumnDtype.STRING),
        ("currency", ColumnDtype.STRING),
        ("event_at", ColumnDtype.INSTANT),
        ("available_at", ColumnDtype.INSTANT),
        ("availability_quality", ColumnDtype.STRING),
        ("source_revision_label", ColumnDtype.STRING),
        ("safety_status", ColumnDtype.STRING),
    ),
    ("subject_entity_id", "target_period_end", "target_at", "event_at"),
)

CONSENSUS_FRAME = _frame(
    "persistra.dataframe.estimates_consensus",
    (
        ("canonical_revision_id", ColumnDtype.STRING),
        ("estimate_measure_id", ColumnDtype.STRING),
        ("measure_version", ColumnDtype.INT),
        ("measure_name", ColumnDtype.STRING),
        ("subject_entity_kind", ColumnDtype.STRING),
        ("subject_entity_id", ColumnDtype.STRING),
        ("source_id", ColumnDtype.STRING),
        ("numeric_kind", ColumnDtype.STRING),
        ("target_kind", ColumnDtype.STRING),
        ("target_period_end", ColumnDtype.DATE),
        ("target_at", ColumnDtype.INSTANT),
        ("contributor_count", ColumnDtype.INT),
        ("mean", ColumnDtype.FLOAT),
        ("median", ColumnDtype.FLOAT),
        ("high", ColumnDtype.FLOAT),
        ("low", ColumnDtype.FLOAT),
        ("standard_deviation", ColumnDtype.FLOAT),
        ("unit_name", ColumnDtype.STRING),
        ("currency", ColumnDtype.STRING),
        ("methodology_content_id", ColumnDtype.STRING),
        ("event_at", ColumnDtype.INSTANT),
        ("available_at", ColumnDtype.INSTANT),
        ("safety_status", ColumnDtype.STRING),
    ),
    ("subject_entity_id", "target_period_end", "target_at", "event_at"),
)

ACTUALS_FRAME = _frame(
    "persistra.dataframe.estimates_actuals",
    (
        ("canonical_revision_id", ColumnDtype.STRING),
        ("estimate_measure_id", ColumnDtype.STRING),
        ("measure_version", ColumnDtype.INT),
        ("measure_name", ColumnDtype.STRING),
        ("subject_entity_kind", ColumnDtype.STRING),
        ("subject_entity_id", ColumnDtype.STRING),
        ("source_id", ColumnDtype.STRING),
        ("numeric_kind", ColumnDtype.STRING),
        ("target_period_end", ColumnDtype.DATE),
        ("value", ColumnDtype.FLOAT),
        ("unit_name", ColumnDtype.STRING),
        ("currency", ColumnDtype.STRING),
        ("filing_id", ColumnDtype.STRING),
        ("raw_fact_revision_id", ColumnDtype.STRING),
        ("fundamental_normalization_id", ColumnDtype.STRING),
        ("event_at", ColumnDtype.INSTANT),
        ("available_at", ColumnDtype.INSTANT),
        ("safety_status", ColumnDtype.STRING),
    ),
    ("subject_entity_id", "target_period_end", "event_at"),
)

MACRO_FRAME = _frame(
    "persistra.dataframe.macro",
    (
        ("canonical_revision_id", ColumnDtype.STRING),
        ("macro_series_id", ColumnDtype.STRING),
        ("series_version", ColumnDtype.INT),
        ("series_name", ColumnDtype.STRING),
        ("macro_release_id", ColumnDtype.STRING),
        ("macro_release_revision_id", ColumnDtype.STRING),
        ("source_id", ColumnDtype.STRING),
        ("numeric_kind", ColumnDtype.STRING),
        ("observation_period_start", ColumnDtype.DATE),
        ("observation_period_end", ColumnDtype.DATE),
        ("release_at", ColumnDtype.INSTANT),
        ("source_release_sequence", ColumnDtype.INT),
        ("source_vintage_key", ColumnDtype.STRING),
        ("vintage_status", ColumnDtype.STRING),
        ("value", ColumnDtype.FLOAT),
        ("is_missing", ColumnDtype.BOOL),
        ("missing_reason_code", ColumnDtype.STRING),
        ("unit_name", ColumnDtype.STRING),
        ("available_at", ColumnDtype.INSTANT),
        ("vintage_completeness", ColumnDtype.STRING),
        ("safety_status", ColumnDtype.STRING),
    ),
    (
        "macro_series_id",
        "observation_period_end",
        "release_at",
        "canonical_revision_id",
    ),
)

BENCHMARK_SERIES_FRAME = _frame(
    "persistra.dataframe.benchmark_series",
    (
        ("canonical_revision_id", ColumnDtype.STRING),
        ("benchmark_id", ColumnDtype.STRING),
        ("benchmark_version", ColumnDtype.INT),
        ("source_id", ColumnDtype.STRING),
        ("series_kind", ColumnDtype.STRING),
        ("interval_start", ColumnDtype.INSTANT),
        ("interval_end", ColumnDtype.INSTANT),
        ("session_date", ColumnDtype.DATE),
        ("value", ColumnDtype.FLOAT),
        ("currency", ColumnDtype.STRING),
        ("calendar_schedule_content_id", ColumnDtype.STRING),
        ("source_methodology_content_id", ColumnDtype.STRING),
        ("available_at", ColumnDtype.INSTANT),
        ("safety_status", ColumnDtype.STRING),
    ),
    ("benchmark_id", "interval_end", "canonical_revision_id"),
)

BENCHMARK_CONSTITUENTS_FRAME = _frame(
    "persistra.dataframe.benchmark_constituents",
    (
        ("canonical_revision_id", ColumnDtype.STRING),
        ("benchmark_id", ColumnDtype.STRING),
        ("benchmark_version", ColumnDtype.INT),
        ("instrument_id", ColumnDtype.STRING),
        ("source_id", ColumnDtype.STRING),
        ("membership_role", ColumnDtype.STRING),
        ("weight", ColumnDtype.FLOAT),
        ("index_shares", ColumnDtype.FLOAT),
        ("divisor_contribution", ColumnDtype.FLOAT),
        ("valid_from", ColumnDtype.INSTANT),
        ("valid_to", ColumnDtype.INSTANT),
        ("methodology_content_id", ColumnDtype.STRING),
        ("available_at", ColumnDtype.INSTANT),
        ("safety_status", ColumnDtype.STRING),
    ),
    ("benchmark_id", "valid_from", "instrument_id", "canonical_revision_id"),
)

RISK_FREE_FRAME = _frame(
    "persistra.dataframe.risk_free_points",
    (
        ("canonical_revision_id", ColumnDtype.STRING),
        ("risk_free_curve_id", ColumnDtype.STRING),
        ("curve_version", ColumnDtype.INT),
        ("source_id", ColumnDtype.STRING),
        ("effective_date", ColumnDtype.DATE),
        ("release_at", ColumnDtype.INSTANT),
        ("available_at", ColumnDtype.INSTANT),
        ("tenor_kind", ColumnDtype.STRING),
        ("tenor_count", ColumnDtype.INT),
        ("maturity_date", ColumnDtype.DATE),
        ("quote_kind", ColumnDtype.STRING),
        ("rate_or_factor", ColumnDtype.FLOAT),
        ("compounding_kind", ColumnDtype.STRING),
        ("compounding_periods_per_year", ColumnDtype.INT),
        ("day_count_kind", ColumnDtype.STRING),
        ("source_curve_manifest_content_id", ColumnDtype.STRING),
        ("safety_status", ColumnDtype.STRING),
    ),
    (
        "risk_free_curve_id",
        "effective_date",
        "tenor_kind",
        "tenor_count",
        "release_at",
    ),
)

