"""Snapshot tests for supported public imports and signatures."""

import inspect

import persistra.analysis
import persistra.data
import persistra.errors
import persistra.integrations
import persistra.integrations.trading_engine
import persistra.model
import persistra.monte_carlo
import persistra.portfolio
import persistra.project
import persistra.research
import persistra.validation
import persistra.viz
from persistra.data import AlphaVantageClient, FredClient
from persistra.model import ResultMetadata


def test_model_public_api_snapshot() -> None:
    assert persistra.model.__all__ == [
        "BarSet",
        "CacheStatus",
        "Catalog",
        "CommoditySpotQuote",
        "EntitlementMode",
        "ExchangeRateQuote",
        "IndexCatalogResult",
        "Instrument",
        "InstrumentKind",
        "InstrumentSearchResult",
        "Listing",
        "MarketStatusResult",
        "OptionChain",
        "OptionContract",
        "OptionType",
        "ProviderSymbol",
        "QuoteSet",
        "ResultMetadata",
        "SchemaDiagnostic",
        "SeriesDefinition",
        "SeriesKind",
        "SeriesSet",
        "TopOfBookSet",
        "VintageDatesResult",
        "VintageSeriesSet",
        "provider_instrument_id",
        "provider_series_id",
    ]


def test_data_public_api_snapshot() -> None:
    assert persistra.data.__all__ == [
        "AcquisitionCachePolicy",
        "AcquisitionFailure",
        "AcquisitionFamily",
        "AcquisitionPlan",
        "AcquisitionReport",
        "AcquisitionRequest",
        "AcquisitionRunner",
        "AcquisitionSuccess",
        "AlphaVantageClient",
        "BarSource",
        "ColumnarExport",
        "ColumnarExportFile",
        "ColumnarFormat",
        "CumulativeDatasetSelection",
        "DuckDBStore",
        "ExactSnapshotSelection",
        "FredCategory",
        "FredClient",
        "FredRelease",
        "FredSeriesCategoriesResult",
        "FredSeriesReleaseResult",
        "FredSeriesSearchResult",
        "FredSeriesSummary",
        "FredSeriesTagsResult",
        "FredTag",
        "InvalidRowPolicy",
        "LocalDataAdapter",
        "LocalFamily",
        "LocalImportSpec",
        "LocalSourceIdentity",
        "LocalValidation",
        "LocalValidationFinding",
        "MigratedSnapshot",
        "OptionChainSource",
        "QuoteSource",
        "RawCacheEntry",
        "RawResponseCache",
        "ReferenceSource",
        "ScalarSeriesSource",
        "SnapshotDiff",
        "SnapshotRow",
        "SnapshotValueChange",
        "StoreExportSelection",
        "StoreMigration",
        "StoreVerification",
        "StoredDataset",
        "StoredOptionSnapshot",
        "StoredPage",
        "StoredResult",
        "StoredSnapshot",
        "acquisition_plan_from_json",
        "acquisition_plan_to_json",
        "align",
        "asof_align",
        "export_store",
        "migrate_store",
        "pivot_bars",
        "pivot_series",
        "resample_bars",
        "synthetic",
        "verify_store",
    ]


def test_synthetic_public_api_snapshot() -> None:
    assert persistra.data.synthetic.__all__ == [
        "SYNTHETIC_NOW",
        "bars",
        "commodity_spot",
        "exchange_rate",
        "index_catalog",
        "market_status",
        "metadata",
        "option_chain",
        "quotes",
        "search",
        "series",
        "top_of_book",
        "treasury_curve",
        "vintage_dates",
        "vintage_series",
    ]


def test_analysis_public_api_snapshot() -> None:
    assert persistra.analysis.__all__ == [
        "absolute_change",
        "absolute_spread",
        "bar_range",
        "basis_point_change",
        "chain_summary",
        "correlation_matrix",
        "covariance_matrix",
        "coverage_summary",
        "cumulative_returns",
        "days_to_expiration",
        "drawdowns",
        "filter_chain",
        "greek_profile",
        "growth_rate",
        "implied_volatility_smile",
        "implied_volatility_surface",
        "intrinsic_value",
        "log_change",
        "log_moneyness",
        "log_returns",
        "midprice",
        "moneyness",
        "option_absolute_spread",
        "option_midprice",
        "option_relative_spread",
        "percentage_change",
        "realized_volatility",
        "rebase",
        "relative_spread",
        "rolling_mean",
        "rolling_standard_deviation",
        "rolling_volatility",
        "rolling_zscore",
        "session_coverage",
        "simple_returns",
        "summary_statistics",
        "time_value",
        "true_range",
        "volume_summary",
        "yield_curve",
        "yield_curve_history",
    ]


def test_research_public_api_snapshot() -> None:
    assert persistra.research.__all__ == [
        "ArtifactIdentity",
        "ArtifactVerification",
        "ArtifactVerificationFinding",
        "BenchmarkComparison",
        "CrossSectionalFactorModelResult",
        "DatasetScope",
        "DelistingPolicy",
        "FactorCovarianceEstimator",
        "FactorPortfolioAttribution",
        "FactorPortfolioForecast",
        "FactorPortfolioForecastStep",
        "FactorPortfolioForecastSuccess",
        "FactorPortfolioForecastUnavailable",
        "FactorPremiaResult",
        "FactorRegressionResult",
        "FactorRiskModel",
        "FamaMacBethResult",
        "FeaturePanel",
        "FeaturePolicy",
        "FeatureSpec",
        "ForwardReturnLabels",
        "GroupSignalResult",
        "InclusionState",
        "InformationCoefficientResult",
        "MissingMembershipPolicy",
        "MultipleTestingResult",
        "NestedTemporalSplit",
        "QuantilePortfolioResult",
        "RegressionCovariance",
        "ResearchManifest",
        "ResearchSummary",
        "RollingFactorPortfolioForecastResult",
        "RollingFactorRegressionResult",
        "SharpeSelectionDiagnostic",
        "SharpeSelectionMethod",
        "SharpeSelectionSuccess",
        "SharpeSelectionUnavailable",
        "TemporalSplit",
        "UniverseMembership",
        "VintagePolicy",
        "VintageSelection",
        "adjust_pvalues",
        "align_universe",
        "apply_universe",
        "attribute_factor_portfolio",
        "build_factor_portfolio_forecast",
        "build_factor_risk_model",
        "build_feature_panel",
        "clip_cross_section",
        "compare_benchmark",
        "create_research_manifest",
        "deflated_sharpe_ratio",
        "environment_distributions",
        "environment_versions",
        "estimate_cross_sectional_factor_returns",
        "expanding_window_splits",
        "fama_macbeth_regression",
        "fit_time_series_factor_model",
        "forward_returns",
        "identify_artifact",
        "information_coefficients",
        "manifest_from_json",
        "manifest_to_json",
        "nested_expanding_window_splits",
        "nested_rolling_window_splits",
        "neutralize_cross_section",
        "probabilistic_sharpe_ratio",
        "project_vintage_history",
        "quantile_portfolios",
        "rank_cross_section",
        "read_research_manifest",
        "research_manifest_schema",
        "rolling_factor_portfolio_forecasts",
        "rolling_time_series_factor_model",
        "rolling_window_splits",
        "runtime_environment",
        "select_vintage",
        "standardize_cross_section",
        "summarize_factor_premia",
        "summarize_groups",
        "summarize_regimes",
        "validate_nested_temporal_split",
        "validate_temporal_split",
        "verify_manifest_artifacts",
        "write_research_manifest",
    ]


def test_monte_carlo_public_api_snapshot() -> None:
    assert persistra.monte_carlo.__all__ == [
        "Distribution",
        "EmpiricalDistribution",
        "GeometricBrownianMotion",
        "MaximumDrawdown",
        "MinimumLevel",
        "MonteCarloExecution",
        "MonteCarloExperiment",
        "MonteCarloModel",
        "MonteCarloResult",
        "MovingBlockBootstrap",
        "MultivariateNormalDistribution",
        "MultivariateNormalReturns",
        "NormalDistribution",
        "PathEvaluationResult",
        "PathEvaluator",
        "PathMetric",
        "PathVolatility",
        "PortfolioBacktestEvaluator",
        "StudentTDistribution",
        "TerminalLevel",
        "TerminalReturn",
        "ThresholdBreach",
        "evaluate_paths",
        "fit_geometric_brownian_motion",
        "run_experiment",
    ]


def test_portfolio_public_api_snapshot() -> None:
    assert persistra.portfolio.__all__ == [
        "ActiveMeanVarianceObjective",
        "AsymmetricTransactionCostPenalty",
        "BacktestPolicies",
        "BacktestResult",
        "BacktestTiming",
        "BorrowPolicy",
        "ConditionalValueAtRiskConstraint",
        "ConditionalValueAtRiskObjective",
        "CorporateAction",
        "CorporateActionKind",
        "CovariancePolicy",
        "CvxpyMixedIntegerSolver",
        "CvxpySolver",
        "DiscretePortfolioProblem",
        "DiscretePortfolioResult",
        "DiscretePortfolioSolver",
        "DiscretePortfolioSolverProblem",
        "EllipsoidalExpectedReturnUncertainty",
        "FactorExposureConstraint",
        "GrossExposureConstraint",
        "GroupedExposureConstraint",
        "LinearExposureConstraint",
        "LinearTransactionCostPenalty",
        "MarketImpactModel",
        "MeanVarianceObjective",
        "MinimumTrackingErrorObjective",
        "MinimumVarianceObjective",
        "MissingCostPolicy",
        "MissingFxPolicy",
        "MissingMembershipPolicy",
        "MissingReturnPolicy",
        "MultiCurrencyPolicy",
        "NetExposureConstraint",
        "NontradeablePolicy",
        "OptimizationFailurePolicy",
        "OverlappingMembershipPolicy",
        "PortfolioConfiguration",
        "PortfolioConstraint",
        "PortfolioConstraints",
        "PortfolioConstructionResult",
        "PortfolioObjective",
        "PortfolioOptimizationPathResult",
        "PortfolioOptimizationResult",
        "PortfolioOptimizationStep",
        "PortfolioPenalty",
        "PortfolioPerformanceReport",
        "PortfolioProblem",
        "PortfolioRiskControl",
        "PortfolioSolver",
        "PortfolioSolverCapabilities",
        "PortfolioSolverProblem",
        "PortfolioSolverResult",
        "PortfolioSolverStatus",
        "QuadraticTransactionCostPenalty",
        "ReturnAdjustment",
        "RiskBudgetConstraint",
        "RiskParityObjective",
        "RobustMeanVarianceObjective",
        "ScipySlsqpSolver",
        "SolverConstraint",
        "TrackingErrorConstraint",
        "TurnoverConstraint",
        "UnavailableShortPolicy",
        "WeightBounds",
        "WeightingMethod",
        "backtest_portfolio",
        "construct_portfolio",
        "optimize_discrete_portfolio",
        "optimize_portfolio",
        "optimize_portfolio_path",
        "portfolio_performance_report",
        "rebalance_schedule",
        "resolve_grouped_exposure",
    ]


def test_integration_public_api_snapshot() -> None:
    assert persistra.integrations.__all__ == ["trading_engine"]
    assert persistra.integrations.trading_engine.__all__ == [
        "INITIAL_STATE_CONTRACT_VERSION",
        "LIFECYCLE_CONTRACT_VERSION",
        "MARKET_DATA_CONTRACT_VERSION",
        "MAX_LIFECYCLE_EVENTS_PER_SLICE",
        "MAX_MARKET_EVENTS_PER_SLICE",
        "RISK_FINANCING_CONTRACT_VERSION",
        "TRADING_ENGINE_CONTRACT_VERSION",
        "TRADING_ENGINE_RESULT_VERSION",
        "CashDividendLifecycleAction",
        "ConservativeBarExecutionPolicy",
        "DistributionLifecycleAction",
        "EngineCapabilities",
        "EngineResourceLimits",
        "EventDeliveryPolicy",
        "ExecutableQuote",
        "ExecutableTrade",
        "ExecutionInstrument",
        "FeeComponent",
        "FeeExecutionPolicy",
        "FinancingPolicy",
        "FractionalEntitlementPolicy",
        "HaltLifecycleEvent",
        "IdentifierChangeLifecycleEvent",
        "InitialCashBalance",
        "InitialFxRate",
        "InitialMark",
        "InitialPortfolioState",
        "InitialPosition",
        "InitialStateReconciliation",
        "InitialStateScenario",
        "InstrumentFeeSchedule",
        "InstrumentRiskPolicy",
        "LifecycleProvenance",
        "LifecycleReplayResult",
        "LifecycleReplayScenario",
        "LifecycleSliceEvents",
        "MarketDataExecutionPolicy",
        "MarketDataModelCapability",
        "MarketDataReplayResult",
        "MarketDataReplayScenario",
        "ObservationProvenance",
        "OrderBookDelete",
        "OrderBookLevel",
        "OrderBookSet",
        "OrderBookSnapshot",
        "OrderBookTrade",
        "ReplayEventClock",
        "ReplaySliceMarketData",
        "ResumeLifecycleEvent",
        "RiskFinancingReplay",
        "RiskFinancingRiskPolicy",
        "RiskFinancingScenario",
        "RiskGroup",
        "RiskGroupLimits",
        "ScheduledCorporateAction",
        "ScheduledLifecycleEvent",
        "SchemaReplayResult",
        "SettlementCalendar",
        "SettlementPolicy",
        "SettlementRule",
        "SplitLifecycleAction",
        "StrategyResponseEvidence",
        "StrategyResponseRejection",
        "StructuredEngineFailureStatus",
        "TerminalDisposition",
        "TerminalLifecycleEvent",
        "TradingEngineContractError",
        "TradingEngineContractSchemas",
        "TradingEngineDiagnostic",
        "TradingEngineDiagnosticCause",
        "TradingEngineDiagnosticContext",
        "TradingEngineProcessError",
        "TradingEngineSuccessCounts",
        "TradingEngineSuccessHashes",
        "TradingEngineSuccessSummary",
        "VenueCalendarPolicy",
        "VenuePhasePolicy",
        "VenueSessionPolicy",
        "bind_engine_status_manifest",
        "bind_initial_state_manifest",
        "bind_lifecycle_manifest",
        "bind_market_data_manifest",
        "bind_risk_financing_manifest",
        "build_initial_state_scenario",
        "build_lifecycle_replay_scenario",
        "build_market_data_replay_scenario",
        "build_risk_financing_scenario",
        "initial_state_scenario_to_json",
        "initial_state_scenario_to_jsonl",
        "lifecycle_scenario_to_json",
        "lifecycle_scenario_to_jsonl",
        "market_data_model_capabilities",
        "market_data_scenario_to_json",
        "market_data_scenario_to_jsonl",
        "reconcile_initial_state_replay",
        "reconcile_lifecycle_replay",
        "reconcile_market_data_replay",
        "reconcile_risk_financing_replay",
        "require_lifecycle_capabilities",
        "require_market_data_capabilities",
        "require_risk_financing_capabilities",
        "risk_financing_scenario_to_json",
        "risk_financing_scenario_to_jsonl",
        "structured_engine_failure",
        "trading_engine_diagnostic_from_json",
        "trading_engine_success_from_json",
        "verify_trading_engine_success",
        "write_initial_state_scenario",
        "write_lifecycle_scenario",
        "write_market_data_scenario",
        "write_risk_financing_scenario",
    ]


def test_visualization_public_api_snapshot() -> None:
    assert persistra.viz.__all__ == [
        "plot_backtest_drawdowns",
        "plot_backtest_performance",
        "plot_backtest_returns",
        "plot_backtest_rolling_volatility",
        "plot_benchmark_comparison",
        "plot_bid_ask_history",
        "plot_candlesticks",
        "plot_constraint_utilization",
        "plot_correlation",
        "plot_cost_attribution",
        "plot_coverage",
        "plot_cumulative_quantile_returns",
        "plot_cumulative_returns",
        "plot_distribution",
        "plot_drawdowns",
        "plot_greek_profile",
        "plot_group_comparison",
        "plot_implied_volatility_smile",
        "plot_implied_volatility_surface",
        "plot_information_coefficient_horizons",
        "plot_information_coefficients",
        "plot_option_chain_prices",
        "plot_option_volume_open_interest",
        "plot_portfolio_exposures",
        "plot_portfolio_turnover",
        "plot_portfolio_weights",
        "plot_predicted_volatility",
        "plot_quantile_capacity",
        "plot_quantile_counts",
        "plot_quantile_returns",
        "plot_quantile_spread",
        "plot_quantile_turnover",
        "plot_rebalance_diagnostics",
        "plot_rebased",
        "plot_return_attribution",
        "plot_returns",
        "plot_risk_contributions",
        "plot_rolling_statistic",
        "plot_rolling_volatility",
        "plot_scalar_series",
        "plot_series",
        "plot_series_change",
        "plot_signal_distribution",
        "plot_signal_ranks",
        "plot_spread_history",
        "plot_stability_comparison",
        "plot_transaction_costs",
        "plot_yield_curve",
        "plot_yield_curve_history",
    ]
    assert not hasattr(persistra.viz, "PriceVolumeAxes")
    assert not hasattr(persistra.viz, "ExecutionPerformanceAxes")
    assert not hasattr(persistra.viz, "ExecutionDiagnosticsAxes")


def test_error_public_api_snapshot() -> None:
    assert persistra.errors.__all__ == [
        "AnalysisError",
        "AuthenticationError",
        "CacheError",
        "DataValidationError",
        "EntitlementError",
        "NoDataError",
        "PersistraError",
        "ProjectError",
        "ProviderError",
        "RateLimitError",
        "ResponseError",
        "StoreError",
        "TransportError",
    ]


def test_project_public_api_snapshot() -> None:
    assert persistra.project.__all__ == [
        "PersistraProject",
        "ProjectValidation",
        "create_project",
        "validate_project",
    ]


def test_validation_public_api_snapshot() -> None:
    assert persistra.validation.__all__ == ["ValidationFinding", "ValidationSeverity"]


def test_alpha_vantage_client_signatures_are_explicit() -> None:
    constructor = inspect.signature(AlphaVantageClient)
    from_env = inspect.signature(AlphaVantageClient.from_env)

    assert "transport_options" not in constructor.parameters
    assert list(from_env.parameters) == [
        "base_url",
        "cache_directory",
        "requests_per_minute",
        "timeout",
        "strict_schema",
        "invalid_row_policy",
        "cache_ages",
        "session",
        "limiter",
    ]
    assert all(
        parameter.kind is inspect.Parameter.KEYWORD_ONLY
        for parameter in from_env.parameters.values()
    )


def test_fred_client_signatures_are_explicit() -> None:
    constructor = inspect.signature(FredClient)
    from_env = inspect.signature(FredClient.from_env)

    assert list(from_env.parameters) == [
        "base_url",
        "cache_directory",
        "timeout",
        "strict_schema",
        "cache_ages",
        "session",
    ]
    assert all(
        parameter.kind is inspect.Parameter.KEYWORD_ONLY
        for parameter in from_env.parameters.values()
    )
    assert "api_key" in constructor.parameters


def test_result_metadata_has_one_construction_path() -> None:
    assert not hasattr(ResultMetadata, "create")
    assert "Mapping[str, Any]" in str(inspect.signature(ResultMetadata))
